name: Check that module was compiled

on:
  push:
    branches:
      - main
      - TMET-4121-Update-GHA-ECS-service-scale-action
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
      - TMET-4121-Update-GHA-ECS-service-scale-action
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  compile-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: TMET-4121-Update-GHA-ECS-service-scale-action

      - name: Install dependencies
        run: npm ci

      - name: Compile code
        run: npm run compile

      - name: Check for diff
        id: git_diff
        run: git diff --exit-code || echo "Changes detected"

      - name: Commit and push changes
        if: steps.git_diff.outputs.changes_detected == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Compile code and commit changes"
          git push origin TMET-4121-Update-GHA-ECS-service-scale-action

      - name: Validate adjust-count usage
        run: |
          grep -q "adjust-count" action.yaml index.js || (echo "adjust-count parameter is missing in the action or index.js file" && exit 1)
