name: Check that module was compiled

on:
  push:
    branches:
      - main
      - TMET-4121-Update-GHA-ECS-service-scale-action
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
      - TMET-4121-Update-GHA-ECS-service-scale-action
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  compile-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Compile code
        run: npm run compile

      - name: Check for diff
        run: |
          if git diff --no-patch --exit-code; then
            echo "No uncommitted changes after compiling."
          else
            echo "Detected uncommitted changes after compiling. Please run 'npm run compile' and commit the changes."
            exit 1
          fi

      - name: Validate adjust-count usage
        run: |
          grep -q "adjust-count" action.yaml index.js || (echo "adjust-count parameter is missing in the action or index.js file" && exit 1)
